type LiteralUnion<T extends string> = T | (string & Record<never, never>);

export const knownIconNames = [
  "Bot",
  "CalendarRange",
  "CalendarDays",
  "Combine",
  "Database",
  "Gauge",
  "Globe",
  "Recycle",
  "Rocket",
  "Server",
  "ServerCog",
  "SquarePen",
  "ArrowRight",
  "ArrowUp",
  "ArrowUpRight",
  "Briefcase",
  "Check",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronsRight",
  "Clock",
  "Diamond",
  "DollarSign",
  "Headset",
  "Headphones",
  "Languages",
  "Link",
  "ListChecks",
  "Mail",
  "MailOpen",
  "MapPin",
  "MessageCircle",
  "Minus",
  "MoveLeft",
  "MoveRight",
  "PencilLine",
  "Phone",
  "Play",
  "Plus",
  "Quote",
  "Search",
  "Send",
  "Settings",
  "ShieldCheck",
  "Star",
  "ThumbsUp",
  "TriangleRight",
  "Trophy",
  "Users",
  "UsersRound",
  "X",
] as const;

export type KnownIconName = (typeof knownIconNames)[number];
export type IconName = LiteralUnion<KnownIconName>;
